#!/usr/bin/env python3
"""Render TrueType faces into 1bpp C tables for the e-paper canvas.

The panel is pure black and white with no greyscale in partial-refresh mode, so
glyphs are thresholded rather than anti-aliased. Anything softer turns into
mud once the waveform quantises it.

Usage: gen_fonts.py <output-dir>
"""

import os
import sys

from PIL import Image, ImageDraw, ImageFont

# Arial ships as plain .ttf files (no .ttc index to guess at), its digits share
# one advance width, and it stays legible when thresholded hard at these sizes.
FACES = "/System/Library/Fonts/Supplemental/"

# The clock uses the narrow cut: "88:88" has to fit inside 400px, and at equal
# width the narrow face buys ~20% more digit height (131px vs 111px).
FONTS = [
    ("clock", "Arial Narrow Bold.ttf", 180, "0123456789:"),
    ("med", "Arial Bold.ttf", 30, None),
    ("small", "Arial Bold.ttf", 18, None),
]

ASCII = "".join(chr(c) for c in range(32, 127))

THRESHOLD = 128


def render(face, size, chars):
    font = ImageFont.truetype(face, size)
    ascent, descent = font.getmetrics()
    glyphs = []
    blob = bytearray()

    for ch in chars:
        advance = int(round(font.getlength(ch)))

        # Draw onto a canvas padded generously in every direction so accents and
        # overhangs cannot be clipped, then crop back to the inked pixels.
        pad = size
        img = Image.new("L", (advance + 2 * pad, ascent + descent + 2 * pad), 0)
        ImageDraw.Draw(img).text((pad, pad), ch, font=font, fill=255)
        img = img.point(lambda v: 255 if v >= THRESHOLD else 0, mode="1")

        box = img.getbbox()
        if box is None:  # whitespace
            glyphs.append((0, 0, 0, 0, advance, len(blob)))
            continue

        x0, y0, x1, y1 = box
        w, h = x1 - x0, y1 - y0
        dx = x0 - pad
        dy = (pad + ascent) - y0  # baseline -> top of bitmap, positive is up

        cropped = img.crop(box)
        stride = (w + 7) // 8
        offset = len(blob)
        pixels = cropped.load()
        for row in range(h):
            packed = bytearray(stride)
            for col in range(w):
                if pixels[col, row]:
                    packed[col >> 3] |= 0x80 >> (col & 7)
            blob += packed

        glyphs.append((w, h, dx, dy, advance, offset))

    return ascent, descent, glyphs, blob


def emit(out_dir, name, face, chars, ascent, descent, glyphs, blob):
    guard = f"ZT_FONT_{name.upper()}_H_"
    lines = [
        "// Generated by tools/gen_fonts.py -- do not edit by hand.",
        f"// Face: {face}",
        "",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        '#include "font.h"',
        "",
        f"static const uint8_t zt_font_{name}_bitmap[] = {{",
    ]

    for i in range(0, len(blob), 16):
        row = ", ".join(f"0x{b:02x}" for b in blob[i : i + 16])
        lines.append(f"    {row},")
    lines.append("};")
    lines.append("")

    lines.append(f"static const zt_glyph_t zt_font_{name}_glyphs[] = {{")
    for ch, (w, h, dx, dy, advance, offset) in zip(chars, glyphs):
        label = ch if ch.isprintable() and ch != " " else "space"
        lines.append(
            f"    {{{w}, {h}, {dx}, {dy}, {advance}, {offset}}},  // '{label}'"
        )
    lines.append("};")
    lines.append("")

    # Positional rather than designated: these headers are pulled into C++17
    # translation units, where designated initialisers are only a GNU extension.
    lines += [
        f"static const zt_font_t zt_font_{name} = {{",
        f"    {ascent},  // ascent",
        f"    {descent},  // descent",
        f"    {ord(chars[0])},  // first",
        f"    {ord(chars[-1])},  // last",
        f"    zt_font_{name}_glyphs,",
        f"    zt_font_{name}_bitmap,",
        "};",
        "",
        f"#endif  // {guard}",
        "",
    ]

    path = os.path.join(out_dir, f"font_{name}.h")
    with open(path, "w") as handle:
        handle.write("\n".join(lines))
    return path, len(blob)


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    out_dir = sys.argv[1]
    os.makedirs(out_dir, exist_ok=True)

    for name, face, size, chars in FONTS:
        chars = chars if chars is not None else ASCII
        # The clock font is only ever indexed by a contiguous run, so the table
        # must stay dense: digits then colon, which is what ASCII order gives.
        chars = "".join(sorted(set(chars)))
        codes = [ord(c) for c in chars]
        if codes != list(range(codes[0], codes[0] + len(codes))):
            sys.exit(f"font {name}: character set must be contiguous ASCII")

        ascent, descent, glyphs, blob = render(FACES + face, size, chars)
        for w, h, dx, dy, advance, offset in glyphs:
            if advance > 0xFFFF or offset > 0xFFFFFFFF:
                sys.exit(f"font {name}: metric overflow")

        path, size_bytes = emit(
            out_dir, name, face, chars, ascent, descent, glyphs, blob
        )
        print(f"{path}: {len(glyphs)} glyphs, {size_bytes} bytes of bitmap")


if __name__ == "__main__":
    main()
